name: Build NoProximityCall

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Install RootHide Theos
        shell: bash
        run: |
          export THEOS="$HOME/theos"

          git clone --recursive \
            https://github.com/roothide/theos.git \
            "$THEOS"


      - name: Install iOS SDK
        shell: bash
        run: |
          export THEOS="$HOME/theos"
          mkdir -p "$THEOS/sdks"

          echo "Downloading iPhoneOS16.5.sdk..."

          curl -fL --retry 5 --retry-delay 3 \
            "https://github.com/theos/sdks/releases/latest/download/iPhoneOS16.5.sdk.tar.xz" \
            -o /tmp/iPhoneOS16.5.sdk.tar.xz


          echo "Extracting SDK..."

          tar -xJf \
            /tmp/iPhoneOS16.5.sdk.tar.xz \
            -C "$THEOS/sdks"


          echo "Installed SDKs:"
          find "$THEOS/sdks" -maxdepth 1 -type d -name "*.sdk"


      - name: Install ldid
        shell: bash
        run: |
          brew install ldid

          echo "ldid version:"
          ldid -v || true


      - name: Check Environment
        shell: bash
        run: |
          export THEOS="$HOME/theos"

          echo "THEOS=$THEOS"

          echo "SDK:"
          ls -lah "$THEOS/sdks"

          echo "ldid:"
          which ldid


      - name: Build
        shell: bash
        run: |
          export THEOS="$HOME/theos"

          make clean
          make package \
            FINALPACKAGE=1 \
            THEOS_PACKAGE_SCHEME=roothide


      - name: Show package
        shell: bash
        run: |
          echo "=============================="
          echo "Generated DEB:"
          echo "=============================="

          ls -lah packages/


      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: NoProximityCall-RootHide
          path: packages/*.deb
          if-no-files-found: error
